### ISSUE TITLE
ESFF problem 

### ISSUE THREAD

**Issue by mohamedmarzouk22** [chaohao2010/ADD-CMAP#1]
I am trying to use ESFF1 force field to optimize the CMAP of .prmtop file of my system but it seems not reading by cpptraj and not modified as well 
![Screen Shot 0002-12-22 at 8 54 22 AM](https://user-images.githubusercontent.com/54627410/102833206-c2f83780-4433-11eb-8167-438cc9358900.png)

**Comment by chaohao2010** [comment]
As shown in the **README.md** and the following lines, the **.prmtop** file with CMAP parameters is NOT supported for *cpptraj* in Amber18 or above. I didn't follow up on the update of Amber, but I think they may change the "mark" as shown in your figure ("CHARMM22 ALL-Hydrogen Topology File for Proteins") at the top of **.prmtop** file with CMAP parameters, so that the recently developed build-in force field with CMAP parameters, such as *ff19SB*, can be compatible with the *cpptraj* and *tleap*  in the new version of Amber. However,  the original **.prmtop** file without CMAP parameters works well with *cpptraj*,  you can try to use that file to analyze the MD trajectories.  

**Note: The new prmtop file with CMAP paramters are not supported in *cpptraj* of AMBER 16 or 18, so the original prmtop file are needed when you use *cpptraj* to analyse the MD trajectories.**
